name: rapid
description: Flutter rapid ui is a library that allows you to build responsive widgets quickly like tailwindcss.
version: 0.0.1
homepage: https://github.com/pacifio/rapid

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
